## Predict Diabetes with K-NN

### Objective: Predict whether a person will be diagnosed with diabetes or not

- Dataset of 768 diagnosed people with or without diabetes

In [382]:
# Libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

## K-NN Algorithm Explanation

 <table>
  <tr>
    <td>
      <img src="KNN_graph1.png" width="200" />
    </td>
        <td>
      <img src="KNN_graph3.png" width="245" />
    </td>
    <td>
      <img src="KNN_graph2.png" width="245" />
    </td>
  </tr>
</table>

- Group items by similar characteristics
- K - the **hyperparameter**, the number of voting members
- K (Number of Neighbors): The 'K' hyperparameter defines the number of nearest neighbors to consider when making predictions for a new data point. For example, if k=3, the algorithm will consider the three nearest neighbors to the query point and make a prediction based on the majority class among those three neighbors (for classification tasks). The choice of 'k' can significantly impact the algorithm's performance.

Choosing the right value of 'k' is crucial because:

- A small 'K' (e.g., k=1) can lead to noise sensitivity and overfitting. The algorithm might be highly influenced by outliers or noise in the data, leading to poor generalization to new data points.
- A large 'K' (e.g., k=20) can lead to oversmoothing and underfitting. The algorithm may lose the ability to capture local patterns in the data, resulting in a more biased model.

### Data Pre-processing

- Values for 'Glucose' and 'Blood Pressure' etc. cannot be accepted as zeros (why?)
- Replace these columns with the mean of the column
- Replace with average since it is the most common for a person

In [383]:
data = pd.read_csv("car.data")
print(len(data))
print(data.head())

1728
  buyingChance maintenance doors people   boot safety  class
0        vhigh       vhigh     2      2  small    low  unacc
1        vhigh       vhigh     2      2  small    med  unacc
2        vhigh       vhigh     2      2  small   high  unacc
3        vhigh       vhigh     2      2    med    low  unacc
4        vhigh       vhigh     2      2    med    med  unacc


In [384]:
# Replace the zeroes 
# strings = ["buyingChance", "maintenance", "doors", "people", "boot", "safety", ]

# Loop through the data and replace zeroes with the column mean
for column in data:
    data[column] = data[column].replace("low", 0)
    data[column] = data[column].replace("med", 1)
    data[column] = data[column].replace("high", 2)
    data[column] = data[column].replace("vhigh", 3)
    
    data[column] = data[column].replace("more", 5)

    data[column] = data[column].replace("5more", 5)

    data[column] = data[column].replace("small", 0)
    data[column] = data[column].replace("big", 2)

    data[column] = data[column].replace("unacc", 0)
    data[column] = data[column].replace("acc", 1)
    data[column] = data[column].replace("good", 2)
    data[column] = data[column].replace("vgood", 2)

    # data[column] = data[column].replace(0, np.nan)
    # mean = int(data[column].mean(skipna=True))
    #data[column] = data[column].replace(np.nan, mean)
    # data[column].fillna(mean, inplace=True)

print(data["class"])
# print(mean)

0       0
1       0
2       0
3       0
4       0
       ..
1723    2
1724    2
1725    0
1726    2
1727    2
Name: class, Length: 1728, dtype: int64


C:\Users\Phoen\AppData\Local\Temp\ipykernel_11628\1371122326.py:9: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[column] = data[column].replace("vhigh", 3)
C:\Users\Phoen\AppData\Local\Temp\ipykernel_11628\1371122326.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[column] = data[column].replace("big", 2)
C:\Users\Phoen\AppData\Local\Temp\ipykernel_11628\1371122326.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call 

In [385]:
# Split the dataset into train and test
x = data.iloc[:, 0:6] # keeps all rows, exclude column 8
y = data.iloc[:, 6] # Label - column 8 , whether or not if you have diabetes
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=0.2)

In [386]:
# Attribute scaling
sc_x = StandardScaler()# sets all data between -1 and 1
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

### Determining the model variables

- The hyperparameter K should be an odd number (why?)
- Use the square root of the length of the y_test set to pick K
- p is the 'diabetic or not'
- Euclidean is the method of measuring the distance between neighbors

In [387]:
# Determine the K value (hyperparaneter)
import math
print(len(y_test))
math.sqrt(len(y_test))

346


18.601075237738275

In [388]:
# Define the model: Init K-NN
classifier = KNeighborsClassifier(n_neighbors=13, p=2, metric='euclidean')
classifier.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=13)

In [389]:
# Predict the test results
y_pred = classifier.predict(x_test)
y_pred

array([1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2,
       0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,

### The Confusion Matrix Analysis Tool

In machine learning, the confusion matrix is a table that is used to evaluate the performance of a classification model, such as a K-Nearest Neighbors (KNN) model. It provides a comprehensive summary of the predictions made by the model on a test dataset, compared to the actual ground truth labels. The confusion matrix has four important metrics: True Positives (TP), False Positives (FP), True Negatives (TN), and False Negatives (FN).

1. True Positives (TP): The number of instances that are correctly predicted as positive (belong to the positive class).

2. False Positives (FP): The number of instances that are incorrectly predicted as positive but actually belong to the negative class.

3. True Negatives (TN): The number of instances that are correctly predicted as negative (belong to the negative class).

4. False Negatives (FN): The number of instances that are incorrectly predicted as negative but actually belong to the positive class.

<table>
    <tr>
        <th>Actual</th>
        <th>Predicted Positive</th>
        <th>Predicted Negative</th>
    </tr>
    <tr>
        <td>Actual Positive </td>
        <td>TP</td>
        <td>FN</td>
    </tr>
    <tr>
        <td>Actual Negative </td>
        <td>FP</td>
        <td>TN</td>
    </tr>
</table>

Here's how to interpret the confusion matrix:

1. TP (True Positives): The model correctly predicted instances that belong to the positive class.

2. FN (False Negatives): The model incorrectly predicted instances as negative when they actually belong to the positive class.

3. FP (False Positives): The model incorrectly predicted instances as positive when they actually belong to the negative class.

4. TN (True Negatives): The model correctly predicted instances that belong to the negative class.

Using these values, we can compute various evaluation metrics, such as **accuracy**, precision, recall (sensitivity), specificity, and **F1-score**, which help us assess the performance of the KNN model on the test data.

- Accuracy = (TP + TN) / (TP + FP + TN + FN)
- Precision = TP / (TP + FP)
- Recall (Sensitivity) = TP / (TP + FN)
- Specificity = TN / (TN + FP)
- F1-Score = 2 * (Precision * Recall) / (Precision + Recall)

A good KNN model will have a high accuracy, precision, recall, specificity, and F1-Score, indicating that it is making correct predictions for both positive and negative classes.


In [390]:
# Evaluate the model
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_test, y_pred))

[[237   3   0]
 [  1  78   0]
 [  0   4  23]]
0.976878612716763


### To interpret the results in the confusion matrix 
[[94, 13], 
[15, 32]]

```
             Predicted Positive    Predicted Negative
Actual Positive        94                13
Actual Negative        15                32
```

Here's how to interpret the values:

1. True Positives (TP): The number of instances that are correctly predicted as positive. In this case, there are 94 true positives, meaning 94 instances were correctly classified as positive (belong to the positive class).

2. False Positives (FP): The number of instances that are incorrectly predicted as positive but actually belong to the negative class. In this case, there are 13 false positives, meaning 13 instances were incorrectly classified as positive when they actually belong to the negative class.

3. True Negatives (TN): The number of instances that are correctly predicted as negative. In this case, there are 32 true negatives, meaning 32 instances were correctly classified as negative (belong to the negative class).

4. False Negatives (FN): The number of instances that are incorrectly predicted as negative but actually belong to the positive class. In this case, there are 15 false negatives, meaning 15 instances were incorrectly classified as negative when they actually belong to the positive class.

Based on these values, we can calculate various evaluation metrics to assess the performance of the classification model:

1. Accuracy: It is the overall correctness of the model's predictions and is calculated as (TP + TN) / (TP + FP + TN + FN). In this case, accuracy = (94 + 32) / (94 + 13 + 15 + 32) ≈ 0.8095 or 80.95%.

2. Precision: It measures the accuracy of the positive predictions and is calculated as TP / (TP + FP). In this case, precision = 94 / (94 + 13) ≈ 0.8785 or 87.85%.

3. Recall (Sensitivity): It measures the ability of the model to correctly identify positive instances and is calculated as TP / (TP + FN). In this case, recall = 94 / (94 + 15) ≈ 0.8621 or 86.21%.

4. F1-Score: It is the harmonic mean of precision and recall and is given by 2 * (Precision * Recall) / (Precision + Recall). In this case, F1-Score = 2 * (0.8785 * 0.8621) / (0.8785 + 0.8621) ≈ 0.8702 or 87.02%.

Our model has a relatively good accuracy, precision, recall, and F1-Score, indicating it performs reasonably well on the given test dataset. However, further analysis and comparison with other models may be necessary for a comprehensive evaluation.